//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 03:28:23 PM EET 
//


package com.yuranos.session.model;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.validation.Valid;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigDecimal;


/**
 * <p>Java class for AvailableInsurance complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AvailableInsurance">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InsuranceType" type="{http://api.thomascook.com/basket/1.0/insurance}InsuranceType"/>
 *         &lt;element name="InsuranceRangeAge" type="{http://api.thomascook.com/basket/1.0/insurance}InsuranceRangeAge"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://api.thomascook.com/basket/1.0/common}displayAttributes"/>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Scheme" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EarlyNetPrice" type="{http://api.thomascook.com/basket/1.0/common}Money" />
 *       &lt;attribute name="GrossPrice" type="{http://api.thomascook.com/basket/1.0/common}Money" />
 *       &lt;attribute name="TripType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Duration" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Notice" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Region" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Default" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AvailableInsurance", namespace = "http://api.thomascook.com/basket/1.0/insurance", propOrder = {
    "insuranceType",
    "insuranceRangeAge"
})
public class AvailableInsurance
    implements Serializable, Equals, HashCode, ToString
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(name = "InsuranceType", required = true)
    @NotNull
    protected InsuranceType insuranceType;
    @XmlElement(name = "InsuranceRangeAge", required = true)
    @NotNull
    @Valid
    protected InsuranceRangeAge insuranceRangeAge;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Scheme")
    protected String scheme;
    @XmlAttribute(name = "Code")
    protected String code;
    @XmlAttribute(name = "EarlyNetPrice")
    @Digits(integer = 10, fraction = 2)
    protected BigDecimal earlyNetPrice;
    @XmlAttribute(name = "GrossPrice")
    @Digits(integer = 10, fraction = 2)
    protected BigDecimal grossPrice;
    @XmlAttribute(name = "TripType")
    protected String tripType;
    @XmlAttribute(name = "Duration")
    protected Integer duration;
    @XmlAttribute(name = "Notice")
    protected Integer notice;
    @XmlAttribute(name = "Region")
    protected String region;
    @XmlAttribute(name = "Default")
    protected Boolean _default;
    @XmlAttribute(name = "Key")
    protected String key;
    @XmlAttribute(name = "DisplayText")
    protected String displayText;

    /**
     * Gets the value of the insuranceType property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceType }
     *     
     */
    public InsuranceType getInsuranceType() {
        return insuranceType;
    }

    /**
     * Sets the value of the insuranceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceType }
     *     
     */
    public void setInsuranceType(InsuranceType value) {
        this.insuranceType = value;
    }

    /**
     * Gets the value of the insuranceRangeAge property.
     * 
     * @return
     *     possible object is
     *     {@link InsuranceRangeAge }
     *     
     */
    public InsuranceRangeAge getInsuranceRangeAge() {
        return insuranceRangeAge;
    }

    /**
     * Sets the value of the insuranceRangeAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsuranceRangeAge }
     *     
     */
    public void setInsuranceRangeAge(InsuranceRangeAge value) {
        this.insuranceRangeAge = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the scheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheme() {
        return scheme;
    }

    /**
     * Sets the value of the scheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheme(String value) {
        this.scheme = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the earlyNetPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEarlyNetPrice() {
        return earlyNetPrice;
    }

    /**
     * Sets the value of the earlyNetPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEarlyNetPrice(BigDecimal value) {
        this.earlyNetPrice = value;
    }

    /**
     * Gets the value of the grossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPrice() {
        return grossPrice;
    }

    /**
     * Sets the value of the grossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPrice(BigDecimal value) {
        this.grossPrice = value;
    }

    /**
     * Gets the value of the tripType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTripType() {
        return tripType;
    }

    /**
     * Sets the value of the tripType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTripType(String value) {
        this.tripType = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDuration(Integer value) {
        this.duration = value;
    }

    /**
     * Gets the value of the notice property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNotice() {
        return notice;
    }

    /**
     * Sets the value of the notice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNotice(Integer value) {
        this.notice = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the default property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDefault() {
        if (_default == null) {
            return false;
        } else {
            return _default;
        }
    }

    /**
     * Sets the value of the default property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefault(Boolean value) {
        this._default = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the displayText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayText() {
        return displayText;
    }

    /**
     * Sets the value of the displayText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayText(String value) {
        this.displayText = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AvailableInsurance)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AvailableInsurance that = ((AvailableInsurance) object);
        {
            InsuranceType lhsInsuranceType;
            lhsInsuranceType = this.getInsuranceType();
            InsuranceType rhsInsuranceType;
            rhsInsuranceType = that.getInsuranceType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "insuranceType", lhsInsuranceType), LocatorUtils.property(thatLocator, "insuranceType", rhsInsuranceType), lhsInsuranceType, rhsInsuranceType)) {
                return false;
            }
        }
        {
            InsuranceRangeAge lhsInsuranceRangeAge;
            lhsInsuranceRangeAge = this.getInsuranceRangeAge();
            InsuranceRangeAge rhsInsuranceRangeAge;
            rhsInsuranceRangeAge = that.getInsuranceRangeAge();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "insuranceRangeAge", lhsInsuranceRangeAge), LocatorUtils.property(thatLocator, "insuranceRangeAge", rhsInsuranceRangeAge), lhsInsuranceRangeAge, rhsInsuranceRangeAge)) {
                return false;
            }
        }
        {
            String lhsID;
            lhsID = this.getID();
            String rhsID;
            rhsID = that.getID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "id", lhsID), LocatorUtils.property(thatLocator, "id", rhsID), lhsID, rhsID)) {
                return false;
            }
        }
        {
            String lhsScheme;
            lhsScheme = this.getScheme();
            String rhsScheme;
            rhsScheme = that.getScheme();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "scheme", lhsScheme), LocatorUtils.property(thatLocator, "scheme", rhsScheme), lhsScheme, rhsScheme)) {
                return false;
            }
        }
        {
            String lhsCode;
            lhsCode = this.getCode();
            String rhsCode;
            rhsCode = that.getCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "code", lhsCode), LocatorUtils.property(thatLocator, "code", rhsCode), lhsCode, rhsCode)) {
                return false;
            }
        }
        {
            BigDecimal lhsEarlyNetPrice;
            lhsEarlyNetPrice = this.getEarlyNetPrice();
            BigDecimal rhsEarlyNetPrice;
            rhsEarlyNetPrice = that.getEarlyNetPrice();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "earlyNetPrice", lhsEarlyNetPrice), LocatorUtils.property(thatLocator, "earlyNetPrice", rhsEarlyNetPrice), lhsEarlyNetPrice, rhsEarlyNetPrice)) {
                return false;
            }
        }
        {
            BigDecimal lhsGrossPrice;
            lhsGrossPrice = this.getGrossPrice();
            BigDecimal rhsGrossPrice;
            rhsGrossPrice = that.getGrossPrice();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "grossPrice", lhsGrossPrice), LocatorUtils.property(thatLocator, "grossPrice", rhsGrossPrice), lhsGrossPrice, rhsGrossPrice)) {
                return false;
            }
        }
        {
            String lhsTripType;
            lhsTripType = this.getTripType();
            String rhsTripType;
            rhsTripType = that.getTripType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "tripType", lhsTripType), LocatorUtils.property(thatLocator, "tripType", rhsTripType), lhsTripType, rhsTripType)) {
                return false;
            }
        }
        {
            Integer lhsDuration;
            lhsDuration = this.getDuration();
            Integer rhsDuration;
            rhsDuration = that.getDuration();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "duration", lhsDuration), LocatorUtils.property(thatLocator, "duration", rhsDuration), lhsDuration, rhsDuration)) {
                return false;
            }
        }
        {
            Integer lhsNotice;
            lhsNotice = this.getNotice();
            Integer rhsNotice;
            rhsNotice = that.getNotice();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "notice", lhsNotice), LocatorUtils.property(thatLocator, "notice", rhsNotice), lhsNotice, rhsNotice)) {
                return false;
            }
        }
        {
            String lhsRegion;
            lhsRegion = this.getRegion();
            String rhsRegion;
            rhsRegion = that.getRegion();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "region", lhsRegion), LocatorUtils.property(thatLocator, "region", rhsRegion), lhsRegion, rhsRegion)) {
                return false;
            }
        }
        {
            boolean lhsDefault;
            lhsDefault = ((this._default!= null)?this.isDefault():false);
            boolean rhsDefault;
            rhsDefault = ((that._default!= null)?that.isDefault():false);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "_default", lhsDefault), LocatorUtils.property(thatLocator, "_default", rhsDefault), lhsDefault, rhsDefault)) {
                return false;
            }
        }
        {
            String lhsKey;
            lhsKey = this.getKey();
            String rhsKey;
            rhsKey = that.getKey();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "key", lhsKey), LocatorUtils.property(thatLocator, "key", rhsKey), lhsKey, rhsKey)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            InsuranceType theInsuranceType;
            theInsuranceType = this.getInsuranceType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "insuranceType", theInsuranceType), currentHashCode, theInsuranceType);
        }
        {
            InsuranceRangeAge theInsuranceRangeAge;
            theInsuranceRangeAge = this.getInsuranceRangeAge();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "insuranceRangeAge", theInsuranceRangeAge), currentHashCode, theInsuranceRangeAge);
        }
        {
            String theID;
            theID = this.getID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "id", theID), currentHashCode, theID);
        }
        {
            String theScheme;
            theScheme = this.getScheme();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "scheme", theScheme), currentHashCode, theScheme);
        }
        {
            String theCode;
            theCode = this.getCode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "code", theCode), currentHashCode, theCode);
        }
        {
            BigDecimal theEarlyNetPrice;
            theEarlyNetPrice = this.getEarlyNetPrice();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "earlyNetPrice", theEarlyNetPrice), currentHashCode, theEarlyNetPrice);
        }
        {
            BigDecimal theGrossPrice;
            theGrossPrice = this.getGrossPrice();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "grossPrice", theGrossPrice), currentHashCode, theGrossPrice);
        }
        {
            String theTripType;
            theTripType = this.getTripType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "tripType", theTripType), currentHashCode, theTripType);
        }
        {
            Integer theDuration;
            theDuration = this.getDuration();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "duration", theDuration), currentHashCode, theDuration);
        }
        {
            Integer theNotice;
            theNotice = this.getNotice();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "notice", theNotice), currentHashCode, theNotice);
        }
        {
            String theRegion;
            theRegion = this.getRegion();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "region", theRegion), currentHashCode, theRegion);
        }
        {
            boolean theDefault;
            theDefault = ((this._default!= null)?this.isDefault():false);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "_default", theDefault), currentHashCode, theDefault);
        }
        {
            String theKey;
            theKey = this.getKey();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "key", theKey), currentHashCode, theKey);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            InsuranceType theInsuranceType;
            theInsuranceType = this.getInsuranceType();
            strategy.appendField(locator, this, "insuranceType", buffer, theInsuranceType);
        }
        {
            InsuranceRangeAge theInsuranceRangeAge;
            theInsuranceRangeAge = this.getInsuranceRangeAge();
            strategy.appendField(locator, this, "insuranceRangeAge", buffer, theInsuranceRangeAge);
        }
        {
            String theID;
            theID = this.getID();
            strategy.appendField(locator, this, "id", buffer, theID);
        }
        {
            String theScheme;
            theScheme = this.getScheme();
            strategy.appendField(locator, this, "scheme", buffer, theScheme);
        }
        {
            String theCode;
            theCode = this.getCode();
            strategy.appendField(locator, this, "code", buffer, theCode);
        }
        {
            BigDecimal theEarlyNetPrice;
            theEarlyNetPrice = this.getEarlyNetPrice();
            strategy.appendField(locator, this, "earlyNetPrice", buffer, theEarlyNetPrice);
        }
        {
            BigDecimal theGrossPrice;
            theGrossPrice = this.getGrossPrice();
            strategy.appendField(locator, this, "grossPrice", buffer, theGrossPrice);
        }
        {
            String theTripType;
            theTripType = this.getTripType();
            strategy.appendField(locator, this, "tripType", buffer, theTripType);
        }
        {
            Integer theDuration;
            theDuration = this.getDuration();
            strategy.appendField(locator, this, "duration", buffer, theDuration);
        }
        {
            Integer theNotice;
            theNotice = this.getNotice();
            strategy.appendField(locator, this, "notice", buffer, theNotice);
        }
        {
            String theRegion;
            theRegion = this.getRegion();
            strategy.appendField(locator, this, "region", buffer, theRegion);
        }
        {
            boolean theDefault;
            theDefault = ((this._default!= null)?this.isDefault():false);
            strategy.appendField(locator, this, "_default", buffer, theDefault);
        }
        {
            String theKey;
            theKey = this.getKey();
            strategy.appendField(locator, this, "key", buffer, theKey);
        }
        {
            String theDisplayText;
            theDisplayText = this.getDisplayText();
            strategy.appendField(locator, this, "displayText", buffer, theDisplayText);
        }
        return buffer;
    }

}
