//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 03:28:23 PM EET 
//


package com.yuranos.session.model;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for CardDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardAliasInfo" type="{http://api.thomascook.com/basket/1.0/payment}CardAliasInfo"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CardType" type="{http://api.thomascook.com/basket/1.0/payment}CardType" />
 *       &lt;attribute name="CardNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="PartialCardNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CardholderName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SecurityCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ExpiryDate" type="{http://api.thomascook.com/basket/1.0/common}ExpiryDate" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardDetails", namespace = "http://api.thomascook.com/basket/1.0/payment", propOrder = {
    "cardAliasInfo"
})
public class CardDetails
    implements Serializable, Equals, HashCode, ToString
{

    private final static long serialVersionUID = 12345L;
    @XmlElement(required = true)
    @NotNull
    @Valid
    protected CardAliasInfo cardAliasInfo;
    @XmlAttribute(name = "CardType")
    protected CardType cardType;
    @XmlAttribute(name = "CardNumber")
    protected String cardNumber;
    @XmlAttribute(name = "PartialCardNumber")
    protected String partialCardNumber;
    @XmlAttribute(name = "CardholderName")
    protected String cardholderName;
    @XmlAttribute(name = "SecurityCode")
    protected String securityCode;
    @XmlAttribute(name = "ExpiryDate")
    @Pattern(regexp = "\\d{4}")
    protected String expiryDate;

    /**
     * Gets the value of the cardAliasInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CardAliasInfo }
     *     
     */
    public CardAliasInfo getCardAliasInfo() {
        return cardAliasInfo;
    }

    /**
     * Sets the value of the cardAliasInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardAliasInfo }
     *     
     */
    public void setCardAliasInfo(CardAliasInfo value) {
        this.cardAliasInfo = value;
    }

    /**
     * Gets the value of the cardType property.
     * 
     * @return
     *     possible object is
     *     {@link CardType }
     *     
     */
    public CardType getCardType() {
        return cardType;
    }

    /**
     * Sets the value of the cardType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardType }
     *     
     */
    public void setCardType(CardType value) {
        this.cardType = value;
    }

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the partialCardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartialCardNumber() {
        return partialCardNumber;
    }

    /**
     * Sets the value of the partialCardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartialCardNumber(String value) {
        this.partialCardNumber = value;
    }

    /**
     * Gets the value of the cardholderName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardholderName() {
        return cardholderName;
    }

    /**
     * Sets the value of the cardholderName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardholderName(String value) {
        this.cardholderName = value;
    }

    /**
     * Gets the value of the securityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityCode() {
        return securityCode;
    }

    /**
     * Sets the value of the securityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityCode(String value) {
        this.securityCode = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof CardDetails)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CardDetails that = ((CardDetails) object);
        {
            CardAliasInfo lhsCardAliasInfo;
            lhsCardAliasInfo = this.getCardAliasInfo();
            CardAliasInfo rhsCardAliasInfo;
            rhsCardAliasInfo = that.getCardAliasInfo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cardAliasInfo", lhsCardAliasInfo), LocatorUtils.property(thatLocator, "cardAliasInfo", rhsCardAliasInfo), lhsCardAliasInfo, rhsCardAliasInfo)) {
                return false;
            }
        }
        {
            CardType lhsCardType;
            lhsCardType = this.getCardType();
            CardType rhsCardType;
            rhsCardType = that.getCardType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cardType", lhsCardType), LocatorUtils.property(thatLocator, "cardType", rhsCardType), lhsCardType, rhsCardType)) {
                return false;
            }
        }
        {
            String lhsCardNumber;
            lhsCardNumber = this.getCardNumber();
            String rhsCardNumber;
            rhsCardNumber = that.getCardNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cardNumber", lhsCardNumber), LocatorUtils.property(thatLocator, "cardNumber", rhsCardNumber), lhsCardNumber, rhsCardNumber)) {
                return false;
            }
        }
        {
            String lhsPartialCardNumber;
            lhsPartialCardNumber = this.getPartialCardNumber();
            String rhsPartialCardNumber;
            rhsPartialCardNumber = that.getPartialCardNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "partialCardNumber", lhsPartialCardNumber), LocatorUtils.property(thatLocator, "partialCardNumber", rhsPartialCardNumber), lhsPartialCardNumber, rhsPartialCardNumber)) {
                return false;
            }
        }
        {
            String lhsCardholderName;
            lhsCardholderName = this.getCardholderName();
            String rhsCardholderName;
            rhsCardholderName = that.getCardholderName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "cardholderName", lhsCardholderName), LocatorUtils.property(thatLocator, "cardholderName", rhsCardholderName), lhsCardholderName, rhsCardholderName)) {
                return false;
            }
        }
        {
            String lhsSecurityCode;
            lhsSecurityCode = this.getSecurityCode();
            String rhsSecurityCode;
            rhsSecurityCode = that.getSecurityCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "securityCode", lhsSecurityCode), LocatorUtils.property(thatLocator, "securityCode", rhsSecurityCode), lhsSecurityCode, rhsSecurityCode)) {
                return false;
            }
        }
        {
            String lhsExpiryDate;
            lhsExpiryDate = this.getExpiryDate();
            String rhsExpiryDate;
            rhsExpiryDate = that.getExpiryDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "expiryDate", lhsExpiryDate), LocatorUtils.property(thatLocator, "expiryDate", rhsExpiryDate), lhsExpiryDate, rhsExpiryDate)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            CardAliasInfo theCardAliasInfo;
            theCardAliasInfo = this.getCardAliasInfo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cardAliasInfo", theCardAliasInfo), currentHashCode, theCardAliasInfo);
        }
        {
            CardType theCardType;
            theCardType = this.getCardType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cardType", theCardType), currentHashCode, theCardType);
        }
        {
            String theCardNumber;
            theCardNumber = this.getCardNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cardNumber", theCardNumber), currentHashCode, theCardNumber);
        }
        {
            String thePartialCardNumber;
            thePartialCardNumber = this.getPartialCardNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "partialCardNumber", thePartialCardNumber), currentHashCode, thePartialCardNumber);
        }
        {
            String theCardholderName;
            theCardholderName = this.getCardholderName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "cardholderName", theCardholderName), currentHashCode, theCardholderName);
        }
        {
            String theSecurityCode;
            theSecurityCode = this.getSecurityCode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "securityCode", theSecurityCode), currentHashCode, theSecurityCode);
        }
        {
            String theExpiryDate;
            theExpiryDate = this.getExpiryDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "expiryDate", theExpiryDate), currentHashCode, theExpiryDate);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            CardAliasInfo theCardAliasInfo;
            theCardAliasInfo = this.getCardAliasInfo();
            strategy.appendField(locator, this, "cardAliasInfo", buffer, theCardAliasInfo);
        }
        {
            CardType theCardType;
            theCardType = this.getCardType();
            strategy.appendField(locator, this, "cardType", buffer, theCardType);
        }
        {
            String theCardNumber;
            theCardNumber = this.getCardNumber();
            strategy.appendField(locator, this, "cardNumber", buffer, theCardNumber);
        }
        {
            String thePartialCardNumber;
            thePartialCardNumber = this.getPartialCardNumber();
            strategy.appendField(locator, this, "partialCardNumber", buffer, thePartialCardNumber);
        }
        {
            String theCardholderName;
            theCardholderName = this.getCardholderName();
            strategy.appendField(locator, this, "cardholderName", buffer, theCardholderName);
        }
        {
            String theSecurityCode;
            theSecurityCode = this.getSecurityCode();
            strategy.appendField(locator, this, "securityCode", buffer, theSecurityCode);
        }
        {
            String theExpiryDate;
            theExpiryDate = this.getExpiryDate();
            strategy.appendField(locator, this, "expiryDate", buffer, theExpiryDate);
        }
        return buffer;
    }

}
