//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 03:28:23 PM EET 
//


package com.yuranos.session.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DistributionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DistributionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Fax"/>
 *     &lt;enumeration value="E-mail"/>
 *     &lt;enumeration value="Mail"/>
 *     &lt;enumeration value="Courier"/>
 *     &lt;enumeration value="Airport collection"/>
 *     &lt;enumeration value="City office"/>
 *     &lt;enumeration value="Hotel desk"/>
 *     &lt;enumeration value="Will call"/>
 *     &lt;enumeration value="Express mail"/>
 *     &lt;enumeration value="Telephone"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DistributionType")
@XmlEnum
public enum DistributionType {


    /**
     * Fax
     * 
     */
    @XmlEnumValue("Fax")
    FAX("Fax"),

    /**
     * E-mail
     * 
     */
    @XmlEnumValue("E-mail")
    E_MAIL("E-mail"),

    /**
     * Mail
     * 
     */
    @XmlEnumValue("Mail")
    MAIL("Mail"),

    /**
     * Courier
     * 
     */
    @XmlEnumValue("Courier")
    COURIER("Courier"),

    /**
     * Airport collection
     * 
     */
    @XmlEnumValue("Airport collection")
    AIRPORT_COLLECTION("Airport collection"),

    /**
     * City office
     * 
     */
    @XmlEnumValue("City office")
    CITY_OFFICE("City office"),

    /**
     * Hotel desk
     * 
     */
    @XmlEnumValue("Hotel desk")
    HOTEL_DESK("Hotel desk"),

    /**
     * Will call
     * 
     */
    @XmlEnumValue("Will call")
    WILL_CALL("Will call"),

    /**
     * Express mail
     * 
     */
    @XmlEnumValue("Express mail")
    EXPRESS_MAIL("Express mail"),

    /**
     * Telephone
     * 
     */
    @XmlEnumValue("Telephone")
    TELEPHONE("Telephone");
    private final String value;

    DistributionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DistributionType fromValue(String v) {
        for (DistributionType c: DistributionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
