//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 03:28:23 PM EET 
//


package com.yuranos.session.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COST"/>
 *     &lt;enumeration value="GET_BASKET"/>
 *     &lt;enumeration value="ADD_EXTRA"/>
 *     &lt;enumeration value="DEL_EXTRA"/>
 *     &lt;enumeration value="UPD_EXTRA"/>
 *     &lt;enumeration value="PRICE_EXTRA"/>
 *     &lt;enumeration value="GET_EXTRA"/>
 *     &lt;enumeration value="ADD_INSURANCE"/>
 *     &lt;enumeration value="DEL_INSURANCE"/>
 *     &lt;enumeration value="UPD_INSURANCE"/>
 *     &lt;enumeration value="GET_INSURANCE"/>
 *     &lt;enumeration value="ADD_PAX"/>
 *     &lt;enumeration value="DEL_PAX"/>
 *     &lt;enumeration value="UPD_PAX"/>
 *     &lt;enumeration value="GET_PAX"/>
 *     &lt;enumeration value="UPD_CONTACT"/>
 *     &lt;enumeration value="GET_CONTACT"/>
 *     &lt;enumeration value="UPD_PAYMENT"/>
 *     &lt;enumeration value="GET_PAYMENT"/>
 *     &lt;enumeration value="BOOK"/>
 *     &lt;enumeration value="COMMIT"/>
 *     &lt;enumeration value="RELEASE"/>
 *     &lt;enumeration value="STATUS"/>
 *     &lt;enumeration value="ADD_PROMOCODE"/>
 *     &lt;enumeration value="GET_PROMOCODE"/>
 *     &lt;enumeration value="SELECT_PREFERENCES"/>
 *     &lt;enumeration value="DELETE_PREFERENCES"/>
 *     &lt;enumeration value="UPDATE_PREFERENCES"/>
 *     &lt;enumeration value="UPDATE_DIRECT_DEBIT"/>
 *     &lt;enumeration value="SETUP_DIRECT_DEBIT"/>
 *     &lt;enumeration value="VIEW_BOOKING_COMRES"/>
 *     &lt;enumeration value="UPDATE_EXTRAS_COMRES"/>
 *     &lt;enumeration value="GET_EXTRAS_COMRES"/>
 *     &lt;enumeration value="POST_EXTRAS_COMRES"/>
 *     &lt;enumeration value="COMMIT_BASKET_COMRES"/>
 *     &lt;enumeration value="GET_PAYMENT_COMRES"/>
 *     &lt;enumeration value="POST_PAYMENT_COMRES"/>
 *     &lt;enumeration value="POST_BOOK_HOLD_COMRES"/>
 *     &lt;enumeration value="POST_BOOK_COMMIT_COMRES"/>
 *     &lt;enumeration value="CHECK_GIFTCARD_BALANCE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OperationTypeEnum")
@XmlEnum
public enum OperationTypeEnum {

    COST,
    GET_BASKET,
    ADD_EXTRA,
    DEL_EXTRA,
    UPD_EXTRA,
    PRICE_EXTRA,
    GET_EXTRA,
    ADD_INSURANCE,
    DEL_INSURANCE,
    UPD_INSURANCE,
    GET_INSURANCE,
    ADD_PAX,
    DEL_PAX,
    UPD_PAX,
    GET_PAX,
    UPD_CONTACT,
    GET_CONTACT,
    UPD_PAYMENT,
    GET_PAYMENT,
    BOOK,
    COMMIT,
    RELEASE,
    STATUS,
    ADD_PROMOCODE,
    GET_PROMOCODE,
    SELECT_PREFERENCES,
    DELETE_PREFERENCES,
    UPDATE_PREFERENCES,
    UPDATE_DIRECT_DEBIT,
    SETUP_DIRECT_DEBIT,
    VIEW_BOOKING_COMRES,
    UPDATE_EXTRAS_COMRES,
    GET_EXTRAS_COMRES,
    POST_EXTRAS_COMRES,
    COMMIT_BASKET_COMRES,
    GET_PAYMENT_COMRES,
    POST_PAYMENT_COMRES,
    POST_BOOK_HOLD_COMRES,
    POST_BOOK_COMMIT_COMRES,
    CHECK_GIFTCARD_BALANCE;

    public String value() {
        return name();
    }

    public static OperationTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
