//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 03:28:23 PM EET 
//


package com.yuranos.session.model;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;
import java.math.BigDecimal;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://api.thomascook.com/basket/1.0/common}MoneyAmount">
 *       &lt;attribute name="maxAge" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="minAge" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ageCode" type="{http://api.thomascook.com/basket/1.0/common}AgeCode" />
 *       &lt;attribute name="passengerID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://api.thomascook.com/basket/1.0/common}SelectedExtraType" />
 *       &lt;attribute name="Percent" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="Fee" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Price", namespace = "http://api.thomascook.com/basket/1.0/extra")
public class Price
    extends MoneyAmount
    implements Serializable, Equals, HashCode, ToString
{

    private final static long serialVersionUID = 12345L;
    @XmlAttribute(name = "maxAge")
    protected String maxAge;
    @XmlAttribute(name = "minAge")
    protected String minAge;
    @XmlAttribute(name = "ageCode")
    protected AgeCode ageCode;
    @XmlAttribute(name = "passengerID")
    protected String passengerID;
    @XmlAttribute(name = "type")
    protected SelectedExtraType type;
    @XmlAttribute(name = "Percent")
    protected BigDecimal percent;
    @XmlAttribute(name = "Fee")
    protected BigDecimal fee;

    /**
     * Gets the value of the maxAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxAge() {
        return maxAge;
    }

    /**
     * Sets the value of the maxAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxAge(String value) {
        this.maxAge = value;
    }

    /**
     * Gets the value of the minAge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinAge() {
        return minAge;
    }

    /**
     * Sets the value of the minAge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinAge(String value) {
        this.minAge = value;
    }

    /**
     * Gets the value of the ageCode property.
     * 
     * @return
     *     possible object is
     *     {@link AgeCode }
     *     
     */
    public AgeCode getAgeCode() {
        return ageCode;
    }

    /**
     * Sets the value of the ageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeCode }
     *     
     */
    public void setAgeCode(AgeCode value) {
        this.ageCode = value;
    }

    /**
     * Gets the value of the passengerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerID() {
        return passengerID;
    }

    /**
     * Sets the value of the passengerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerID(String value) {
        this.passengerID = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedExtraType }
     *     
     */
    public SelectedExtraType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedExtraType }
     *     
     */
    public void setType(SelectedExtraType value) {
        this.type = value;
    }

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPercent() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPercent(BigDecimal value) {
        this.percent = value;
    }

    /**
     * Gets the value of the fee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFee(BigDecimal value) {
        this.fee = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Price)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final Price that = ((Price) object);
        {
            String lhsMaxAge;
            lhsMaxAge = this.getMaxAge();
            String rhsMaxAge;
            rhsMaxAge = that.getMaxAge();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maxAge", lhsMaxAge), LocatorUtils.property(thatLocator, "maxAge", rhsMaxAge), lhsMaxAge, rhsMaxAge)) {
                return false;
            }
        }
        {
            String lhsMinAge;
            lhsMinAge = this.getMinAge();
            String rhsMinAge;
            rhsMinAge = that.getMinAge();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "minAge", lhsMinAge), LocatorUtils.property(thatLocator, "minAge", rhsMinAge), lhsMinAge, rhsMinAge)) {
                return false;
            }
        }
        {
            AgeCode lhsAgeCode;
            lhsAgeCode = this.getAgeCode();
            AgeCode rhsAgeCode;
            rhsAgeCode = that.getAgeCode();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "ageCode", lhsAgeCode), LocatorUtils.property(thatLocator, "ageCode", rhsAgeCode), lhsAgeCode, rhsAgeCode)) {
                return false;
            }
        }
        {
            String lhsPassengerID;
            lhsPassengerID = this.getPassengerID();
            String rhsPassengerID;
            rhsPassengerID = that.getPassengerID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "passengerID", lhsPassengerID), LocatorUtils.property(thatLocator, "passengerID", rhsPassengerID), lhsPassengerID, rhsPassengerID)) {
                return false;
            }
        }
        {
            SelectedExtraType lhsType;
            lhsType = this.getType();
            SelectedExtraType rhsType;
            rhsType = that.getType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "type", lhsType), LocatorUtils.property(thatLocator, "type", rhsType), lhsType, rhsType)) {
                return false;
            }
        }
        {
            BigDecimal lhsPercent;
            lhsPercent = this.getPercent();
            BigDecimal rhsPercent;
            rhsPercent = that.getPercent();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "percent", lhsPercent), LocatorUtils.property(thatLocator, "percent", rhsPercent), lhsPercent, rhsPercent)) {
                return false;
            }
        }
        {
            BigDecimal lhsFee;
            lhsFee = this.getFee();
            BigDecimal rhsFee;
            rhsFee = that.getFee();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "fee", lhsFee), LocatorUtils.property(thatLocator, "fee", rhsFee), lhsFee, rhsFee)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            String theMaxAge;
            theMaxAge = this.getMaxAge();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "maxAge", theMaxAge), currentHashCode, theMaxAge);
        }
        {
            String theMinAge;
            theMinAge = this.getMinAge();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "minAge", theMinAge), currentHashCode, theMinAge);
        }
        {
            AgeCode theAgeCode;
            theAgeCode = this.getAgeCode();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "ageCode", theAgeCode), currentHashCode, theAgeCode);
        }
        {
            String thePassengerID;
            thePassengerID = this.getPassengerID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "passengerID", thePassengerID), currentHashCode, thePassengerID);
        }
        {
            SelectedExtraType theType;
            theType = this.getType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "type", theType), currentHashCode, theType);
        }
        {
            BigDecimal thePercent;
            thePercent = this.getPercent();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "percent", thePercent), currentHashCode, thePercent);
        }
        {
            BigDecimal theFee;
            theFee = this.getFee();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "fee", theFee), currentHashCode, theFee);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            String theMaxAge;
            theMaxAge = this.getMaxAge();
            strategy.appendField(locator, this, "maxAge", buffer, theMaxAge);
        }
        {
            String theMinAge;
            theMinAge = this.getMinAge();
            strategy.appendField(locator, this, "minAge", buffer, theMinAge);
        }
        {
            AgeCode theAgeCode;
            theAgeCode = this.getAgeCode();
            strategy.appendField(locator, this, "ageCode", buffer, theAgeCode);
        }
        {
            String thePassengerID;
            thePassengerID = this.getPassengerID();
            strategy.appendField(locator, this, "passengerID", buffer, thePassengerID);
        }
        {
            SelectedExtraType theType;
            theType = this.getType();
            strategy.appendField(locator, this, "type", buffer, theType);
        }
        {
            BigDecimal thePercent;
            thePercent = this.getPercent();
            strategy.appendField(locator, this, "percent", buffer, thePercent);
        }
        {
            BigDecimal theFee;
            theFee = this.getFee();
            strategy.appendField(locator, this, "fee", buffer, theFee);
        }
        return buffer;
    }

}
