//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.07 at 03:28:23 PM EET 
//


package com.yuranos.session.model;

import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for SelectedExtraPassenger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectedExtraPassenger">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="passengerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="seat" type="{http://api.thomascook.com/basket/1.0/extra}SelectedSeat" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectedExtraPassenger", namespace = "http://api.thomascook.com/basket/1.0/extra", propOrder = {
    "passengerId",
    "dateOfBirth",
    "seat"
})
public class SelectedExtraPassenger
    implements Serializable, Equals, HashCode, ToString
{

    private final static long serialVersionUID = 12345L;
    protected String passengerId;
    protected String dateOfBirth;
    @Valid
    protected SelectedSeat seat;

    /**
     * Gets the value of the passengerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerId() {
        return passengerId;
    }

    /**
     * Sets the value of the passengerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerId(String value) {
        this.passengerId = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfBirth(String value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the seat property.
     * 
     * @return
     *     possible object is
     *     {@link SelectedSeat }
     *     
     */
    public SelectedSeat getSeat() {
        return seat;
    }

    /**
     * Sets the value of the seat property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectedSeat }
     *     
     */
    public void setSeat(SelectedSeat value) {
        this.seat = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof SelectedExtraPassenger)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final SelectedExtraPassenger that = ((SelectedExtraPassenger) object);
        {
            String lhsPassengerId;
            lhsPassengerId = this.getPassengerId();
            String rhsPassengerId;
            rhsPassengerId = that.getPassengerId();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "passengerId", lhsPassengerId), LocatorUtils.property(thatLocator, "passengerId", rhsPassengerId), lhsPassengerId, rhsPassengerId)) {
                return false;
            }
        }
        {
            String lhsDateOfBirth;
            lhsDateOfBirth = this.getDateOfBirth();
            String rhsDateOfBirth;
            rhsDateOfBirth = that.getDateOfBirth();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dateOfBirth", lhsDateOfBirth), LocatorUtils.property(thatLocator, "dateOfBirth", rhsDateOfBirth), lhsDateOfBirth, rhsDateOfBirth)) {
                return false;
            }
        }
        {
            SelectedSeat lhsSeat;
            lhsSeat = this.getSeat();
            SelectedSeat rhsSeat;
            rhsSeat = that.getSeat();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "seat", lhsSeat), LocatorUtils.property(thatLocator, "seat", rhsSeat), lhsSeat, rhsSeat)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String thePassengerId;
            thePassengerId = this.getPassengerId();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "passengerId", thePassengerId), currentHashCode, thePassengerId);
        }
        {
            String theDateOfBirth;
            theDateOfBirth = this.getDateOfBirth();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dateOfBirth", theDateOfBirth), currentHashCode, theDateOfBirth);
        }
        {
            SelectedSeat theSeat;
            theSeat = this.getSeat();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "seat", theSeat), currentHashCode, theSeat);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String thePassengerId;
            thePassengerId = this.getPassengerId();
            strategy.appendField(locator, this, "passengerId", buffer, thePassengerId);
        }
        {
            String theDateOfBirth;
            theDateOfBirth = this.getDateOfBirth();
            strategy.appendField(locator, this, "dateOfBirth", buffer, theDateOfBirth);
        }
        {
            SelectedSeat theSeat;
            theSeat = this.getSeat();
            strategy.appendField(locator, this, "seat", buffer, theSeat);
        }
        return buffer;
    }

}
